export const TRANSLATIONS: Record<string, any> = {
    'pt-br': {
        nav: { home: 'Home', sim: 'Simular', entries: 'Faturas', admin: 'Ajustes' },
        dash: { greet: 'Fala, brother!', sub: 'Bora decolar hoje?', mission: 'Missão de Hoje', coffee_title: 'Desafio do Café ☕', coffee_text: 'Mano, se liga: se trocar o café da rua por um em casa hoje, você aporta **R$ 15** a mais no seu projeto. Partiu?', coffee_cta: 'Aceitar Desafio', income: 'RECEITAS', expense: 'DESPESAS', projects: 'Projetos Ativos', view_all: 'Ver todos' },
        entries: { title: 'Lançamentos', sub: 'Se liga no que tá saindo da conta...', scanner: 'Scanner IA', manual: 'Manual', camera: 'Câmera', text: 'Texto', upload: 'Arquivo', open_scanner: 'Abrir Scanner', scan_cta: 'DETECTAR AGORA', history: 'Histórico', filters: 'Filtros', start: 'Início', end: 'Fim', save: 'Salvar no Fluxo', desc_placeholder: 'Ex: Churrasco da Firma', val_placeholder: '0,00', launch_cta: 'Lançar Agora', category: 'Categoria', freq: 'Frequência', once: 'Única', monthly: 'Mensal', yearly: 'Anual', paste_info: 'Clique para upload ou cole (Ctrl+V)' },
        admin: { title: 'Ajustes da Firma', sub: 'Configure sua experiência, brother.', level: 'Nível Investidor Pro', style: 'Aparência e Estilo', theme: 'Tema do App', theme_light: 'Claro', theme_dark: 'Escuro', theme_hybrid: 'Híbrido', color: 'Cor da Firma', lang: 'Idioma', current_lang: 'Português (Brasil)', security: 'Segurança e Blindagem', biometrics: 'Login Biométrico', '2fa': 'Autenticação 2FA', pass: 'Alterar Senha de Acesso', logout: 'Sair da Firma' },
        sim: { title: 'Simuladores', investment: 'Investimento', finance: 'Financiamento', consortium: 'Consórcio', initial: 'Valor Inicial', monthly: 'Valor Mensal', result: 'Resultado Estimado', analyze: 'Veredito Brother IA' }
    },
    'en': {
        nav: { home: 'Home', sim: 'Simulate', entries: 'Bills', admin: 'Settings' },
        dash: { greet: 'Hey, brother!', sub: 'Ready to take off?', mission: 'Today\'s Mission', coffee_title: 'Coffee Challenge ☕', coffee_text: 'Look, if you swap that street coffee for one at home today, you save **$15** more for your project. Deal?', coffee_cta: 'Accept Challenge', income: 'INCOME', expense: 'EXPENSES', projects: 'Active Projects', view_all: 'View all' },
        entries: { title: 'Transactions', sub: 'Watch what\'s leaving your account...', scanner: 'AI Scanner', manual: 'Manual', camera: 'Camera', text: 'Text', upload: 'File', open_scanner: 'Open Scanner', scan_cta: 'DETECT NOW', history: 'History', filters: 'Filters', start: 'Start', end: 'End', save: 'Save to Flow', desc_placeholder: 'Ex: Company BBQ', val_placeholder: '0.00', launch_cta: 'Launch Now', category: 'Category', freq: 'Frequency', once: 'Once', monthly: 'Monthly', yearly: 'Yearly', paste_info: 'Click to upload or paste (Ctrl+V)' },
        admin: { title: 'HQ Settings', sub: 'Setup your experience, brother.', level: 'Pro Investor Level', style: 'Style & Appearance', theme: 'App Theme', theme_light: 'Light', theme_dark: 'Dark', theme_hybrid: 'Hybrid', color: 'Company Color', lang: 'Language', current_lang: 'English (US)', security: 'Security & Shield', biometrics: 'Biometric Login', '2fa': '2FA Auth', pass: 'Change Password', logout: 'Logout' },
        sim: { title: 'Simulators', investment: 'Investment', finance: 'Financing', consortium: 'Consortium', initial: 'Initial Value', monthly: 'Monthly Value', result: 'Estimated Result', analyze: 'AI Brother Verdict' }
    }
};
